Repository hmcts/aks-cft-deploy, pull requests merged in 2023-05, with the labels that each got.

#428 Switch default to ithc after removing sbox
  azure-pipelines.yml
Labels: ithc-genesis/add-or-update, ithc-network-rg/no-changes, ithc-network/add-or-update, ithc-managed-identity/no-changes, ithc-aks/add-or-update, ithc-aks-mis/no-changes

#429 Remove ptlsbox from main for state move
  azure-pipelines.yml
Labels: ithc-genesis/add-or-update, ithc-network-rg/no-changes, ithc-network/add-or-update, ithc-managed-identity/no-changes, ithc-aks/add-or-update, ithc-aks-mis/no-changes

#430 Remove ITHC from main for state move
  azure-pipelines.yml
Labels: perftest-genesis/add-or-update, perftest-network-rg/no-changes, perftest-network/add-or-update, perftest-managed-identity/no-changes, perftest-aks/add-or-update, perftest-aks-mis/no-changes

#431 Remove envs for state mv besides ptl & prod
  azure-pipelines.yml
Labels: ptl-genesis/add-or-update, ptl-network-rg/no-changes, ptl-network/no-changes, ptl-managed-identity/no-changes, ptl-aks/no-changes

#433 DTSPO-11646 Remove state move blocks
  components/aks-mis/state-moved.tf
  components/aks/state-moved.tf
Labels: sbox-genesis/add-or-update, sbox-network-rg/no-changes, sbox-network/add-or-update, sbox-managed-identity/no-changes, sbox-aks/add-or-update, sbox-aks-mis/no-changes

#434 Adds routes from ptl to sds test and ithc
  environments/network/ptl.tfvars
Labels: sbox-genesis/add-or-update, sbox-network-rg/no-changes, sbox-network/add-or-update, sbox-managed-identity/no-changes, sbox-aks/add-or-update, sbox-aks-mis/no-changes

#435 fix: added routes to management vnet
  environments/network/ptl.tfvars
Labels: sbox-genesis/add-or-update, sbox-network-rg/no-changes, sbox-network/add-or-update, sbox-managed-identity/no-changes, sbox-aks/add-or-update, sbox-aks-mis/no-changes

#438 Disabling pluto run on updatecli workflow
  .github/workflows/run-updatecli.yaml
Labels: sbox-genesis/add-or-update, sbox-network-rg/no-changes, sbox-network/add-or-update, sbox-managed-identity/no-changes, sbox-aks/add-or-update, sbox-aks-mis/no-changes

#442 update service connection name for PlatformOperations ADO
  azure-pipelines.yml
  pipeline-scripts/builds-check.sh
Labels: sbox-genesis/add-or-update, sbox-network-rg/add-or-update

#455 Add-new-ip-subnets-for-jump-box-roues
  environments/network/ptl.tfvars
Labels: sbox-genesis/add-or-update
