Repository hmcts/aks-cft-deploy, pull requests merged in 2025-06, with the labels that each got.

#724 Revert "Bootstrap Flux with GitHub App secret instead of SSH Deploy key"
  azure-pipelines.yml
  bootstrap/bootstrap.sh
  bootstrap/scripts/create-flux-githubkey-secret.sh
  bootstrap/scripts/create-github-app-secret.sh
  bootstrap/scripts/install-flux.sh
Labels: 766: Genesis_sbox - Genesis/add-or-update, 766: Network_sbox - NetworkRg/no-changes, 766: Aks_sbox - DeployInfrastructuremis/no-changes, 766: Genesis_ptlsbox - Genesis/add-or-update, 766: Genesis_aat - Genesis/add-or-update, 766: Genesis_demo - Genesis/add-or-update, 766: Genesis_perftest - Genesis/add-or-update, 766: Genesis_ithc - Genesis/add-or-update, 766: Network_preview - NetworkRg/no-changes, 766: Network_ptlsbox - NetworkRg/no-changes, 766: Network_demo - NetworkRg/no-changes, 766: Network_perftest - NetworkRg/no-changes, 766: Network_aat - NetworkRg/no-changes, 766: Network_ithc - NetworkRg/no-changes, 766: Aks_ptlsbox - DeployInfrastructure/no-changes, 766: Aks_ithc - DeployInfrastructure/add-or-update, 766: Aks_aat - DeployInfrastructure/no-changes, 766: Aks_ithc - DeployInfrastructuremis/no-changes, 766: Aks_demo - DeployInfrastructuremis/no-changes, 766: Aks_aat - DeployInfrastructuremis/no-changes, 766: Genesis_ptl - Genesis/add-or-update, 766: Genesis_prod - Genesis/add-or-update, 766: Network_ptl - NetworkRg/no-changes, 766: Network_prod - NetworkRg/no-changes, 766: Aks_prod - DeployInfrastructure/add-or-update, 766: Aks_ptl - DeployInfrastructuremis/no-changes, 766: Aks_prod - DeployInfrastructuremis/no-changes, 766: Genesis_preview - Genesis/no-changes, 766: Network_aat - DeployInfrastructure/no-changes, 766: Aks_sbox - DeployInfrastructure/no-changes, 766: Aks_demo - DeployInfrastructure/no-changes, 766: Aks_ptl - DeployInfrastructure/add-or-update, 766: Aks_preview - DeployInfrastructure/destroy

#726 Upgrade 00 PTL aks to 1.32
  environments/aks/ptl.tfvars
Labels: 766: Genesis_sbox - Genesis/add-or-update, 766: Network_sbox - NetworkRg/no-changes, 766: Aks_sbox - DeployInfrastructuremis/no-changes, 766: Genesis_preview - Genesis/add-or-update, 766: Genesis_ptlsbox - Genesis/add-or-update, 766: Genesis_aat - Genesis/add-or-update, 766: Genesis_demo - Genesis/add-or-update, 766: Genesis_perftest - Genesis/add-or-update, 766: Genesis_ithc - Genesis/add-or-update, 766: Network_preview - NetworkRg/no-changes, 766: Network_ptlsbox - NetworkRg/no-changes, 766: Network_demo - NetworkRg/no-changes, 766: Network_perftest - NetworkRg/no-changes, 766: Network_aat - NetworkRg/no-changes, 766: Network_ithc - NetworkRg/no-changes, 766: Aks_ptlsbox - DeployInfrastructure/no-changes, 766: Aks_aat - DeployInfrastructure/no-changes, 766: Aks_ithc - DeployInfrastructuremis/no-changes, 766: Aks_demo - DeployInfrastructuremis/no-changes, 766: Aks_aat - DeployInfrastructuremis/no-changes, 766: Genesis_ptl - Genesis/add-or-update, 766: Genesis_prod - Genesis/add-or-update, 766: Network_ptl - NetworkRg/no-changes, 766: Network_prod - NetworkRg/no-changes, 766: Aks_prod - DeployInfrastructure/add-or-update, 766: Aks_ptl - DeployInfrastructuremis/no-changes, 766: Aks_prod - DeployInfrastructuremis/no-changes, 766: Network_aat - DeployInfrastructure/no-changes, 766: Network_ptl - DeployInfrastructure/no-changes, 766: Aks_sbox - DeployInfrastructure/no-changes, 766: Aks_preview - DeployInfrastructure/no-changes, 766: Aks_demo - DeployInfrastructure/no-changes, 766: Aks_ptl - DeployInfrastructure/add-or-update, 766: Aks_ithc - DeployInfrastructure/no-changes

#727 Bootstrap Flux with GitHub App secret instead of SSH Deploy key
  bootstrap/bootstrap.sh
  bootstrap/scripts/create-flux-githubkey-secret.sh
  bootstrap/scripts/create-github-app-secret.sh
  bootstrap/scripts/install-flux.sh
Labels: 766: Genesis_sbox - Genesis/add-or-update, 766: Network_sbox - NetworkRg/no-changes, 766: Aks_sbox - DeployInfrastructure/add-or-update, 766: Aks_sbox - DeployInfrastructuremis/no-changes, 766: Genesis_preview - Genesis/add-or-update, 766: Genesis_ptlsbox - Genesis/add-or-update, 766: Genesis_aat - Genesis/add-or-update, 766: Genesis_demo - Genesis/add-or-update, 766: Genesis_perftest - Genesis/add-or-update, 766: Genesis_ithc - Genesis/add-or-update, 766: Network_preview - NetworkRg/no-changes, 766: Network_ptlsbox - NetworkRg/no-changes, 766: Network_demo - NetworkRg/no-changes, 766: Network_perftest - NetworkRg/no-changes, 766: Network_aat - NetworkRg/no-changes, 766: Network_ithc - NetworkRg/no-changes, 766: Aks_ptlsbox - DeployInfrastructure/no-changes, 766: Aks_ithc - DeployInfrastructure/add-or-update, 766: Aks_aat - DeployInfrastructure/no-changes, 766: Aks_ithc - DeployInfrastructuremis/no-changes, 766: Aks_demo - DeployInfrastructuremis/no-changes, 766: Aks_aat - DeployInfrastructuremis/no-changes, 766: Genesis_ptl - Genesis/add-or-update, 766: Genesis_prod - Genesis/add-or-update, 766: Network_ptl - NetworkRg/no-changes, 766: Network_prod - NetworkRg/no-changes, 766: Aks_ptl - DeployInfrastructure/no-changes, 766: Aks_prod - DeployInfrastructure/add-or-update, 766: Aks_ptl - DeployInfrastructuremis/no-changes, 766: Aks_prod - DeployInfrastructuremis/no-changes, 766: Network_aat - DeployInfrastructure/no-changes, 766: Network_ptl - DeployInfrastructure/no-changes, 766: Aks_demo - DeployInfrastructure/add-or-update
