Repository hmcts/aks-cft-deploy, pull requests merged in 2025-04, with the labels that each got.

#698 DTSPO 22075 - Revert PR #694
  azure-pipelines.yml
  components/aks/aks.tf
Labels: Network_sbox - NetworkRg/no-changes, Network_sbox - DeployInfrastructure/no-changes, Aks_sbox - DeployInfrastructuremis/no-changes, Network_demo - NetworkRg/no-changes, Network_perftest - NetworkRg/no-changes, Network_ithc - NetworkRg/no-changes, Network_ptlsbox - NetworkRg/no-changes, Network_preview - NetworkRg/no-changes, Network_aat - NetworkRg/no-changes, Network_ptlsbox - DeployInfrastructure/no-changes, Aks_demo - DeployInfrastructuremis/no-changes, Aks_ithc - DeployInfrastructuremis/no-changes, Aks_perftest - DeployInfrastructuremis/no-changes, Aks_preview - DeployInfrastructuremis/no-changes, Aks_ptlsbox - DeployInfrastructuremis/no-changes, Aks_aat - DeployInfrastructuremis/no-changes, Network_ptl - NetworkRg/no-changes, Network_prod - NetworkRg/no-changes, Managed_Identity_ptl - Managed_Identity/no-changes, Aks_ptl - DeployInfrastructure/no-changes, Aks_prod - DeployInfrastructure/add-or-update, Aks_ptl - DeployInfrastructuremis/no-changes, Aks_prod - DeployInfrastructuremis/no-changes, Aks_aat - DeployInfrastructure/no-changes, Aks_sbox - DeployInfrastructure/destroy, Aks_preview - DeployInfrastructure/destroy, Aks_ithc - DeployInfrastructure/destroy, Aks_ptlsbox - DeployInfrastructure/destroy, Aks_demo - DeployInfrastructure/destroy, Aks_perftest - DeployInfrastructure/destroy, Network_demo - DeployInfrastructure/add-or-update, Network_aat - DeployInfrastructure/add-or-update, Network_ithc - DeployInfrastructure/add-or-update, Network_prod - DeployInfrastructure/add-or-update, Network_ptl - DeployInfrastructure/add-or-update, Genesis_sbox - Genesis/add-or-update, Genesis_ptlsbox - Genesis/add-or-update, Genesis_perftest - Genesis/add-or-update, Genesis_preview - Genesis/add-or-update, Genesis_aat - Genesis/add-or-update, Genesis_demo - Genesis/add-or-update, Genesis_ithc - Genesis/add-or-update, Genesis_ptl - Genesis/add-or-update, Genesis_prod - Genesis/add-or-update

#699 DTSPO-24310: Updating cluster bootstrapping to use workload identity for flux-system
  azure-pipelines.yml
  bootstrap/scripts/deploy-flux-util-functions.sh
  bootstrap/scripts/install-flux.sh
Labels: Genesis_sbox - Genesis/no-changes, Network_sbox - NetworkRg/no-changes, Network_sbox - DeployInfrastructure/no-changes, Aks_sbox - DeployInfrastructure/add-or-update, Aks_sbox - DeployInfrastructuremis/no-changes, Network_demo - NetworkRg/no-changes, Network_perftest - NetworkRg/no-changes, Network_ithc - NetworkRg/no-changes, Network_ptlsbox - NetworkRg/no-changes, Network_preview - NetworkRg/no-changes, Network_aat - NetworkRg/no-changes, Network_ptlsbox - DeployInfrastructure/no-changes, Aks_demo - DeployInfrastructure/add-or-update, Aks_ithc - DeployInfrastructure/add-or-update, Aks_preview - DeployInfrastructure/add-or-update, Aks_perftest - DeployInfrastructure/add-or-update, Aks_ptlsbox - DeployInfrastructure/no-changes, Aks_demo - DeployInfrastructuremis/no-changes, Aks_ithc - DeployInfrastructuremis/no-changes, Aks_perftest - DeployInfrastructuremis/no-changes, Aks_preview - DeployInfrastructuremis/no-changes, Aks_ptlsbox - DeployInfrastructuremis/no-changes, Aks_aat - DeployInfrastructuremis/no-changes, Aks_aat - DeployInfrastructure/no-changes, Managed_Identity_aat - Managed_Identity/no-changes, Network_demo - DeployInfrastructure/add-or-update, Network_aat - DeployInfrastructure/add-or-update, Network_ithc - DeployInfrastructure/add-or-update, Genesis_ptlsbox - Genesis/add-or-update, Genesis_perftest - Genesis/add-or-update, Genesis_preview - Genesis/add-or-update, Genesis_aat - Genesis/add-or-update, Genesis_demo - Genesis/add-or-update, Genesis_ithc - Genesis/add-or-update

#700 DTSPO-24319: Readding PTL to azure-pipeline steps for bootstrapping rollout
  azure-pipelines.yml
Labels: Network_sbox - NetworkRg/no-changes, Network_sbox - DeployInfrastructure/no-changes, Aks_sbox - DeployInfrastructuremis/no-changes, Genesis_preview - Genesis/no-changes, Network_demo - NetworkRg/no-changes, Network_perftest - NetworkRg/no-changes, Network_ithc - NetworkRg/no-changes, Network_ptlsbox - NetworkRg/no-changes, Network_preview - NetworkRg/no-changes, Network_aat - NetworkRg/no-changes, Network_demo - DeployInfrastructure/no-changes, Network_ithc - DeployInfrastructure/no-changes, Network_perftest - DeployInfrastructure/no-changes, Network_ptlsbox - DeployInfrastructure/no-changes, Network_preview - DeployInfrastructure/no-changes, Network_aat - DeployInfrastructure/no-changes, Aks_ithc - DeployInfrastructure/add-or-update, Aks_ptlsbox - DeployInfrastructure/no-changes, Aks_demo - DeployInfrastructuremis/no-changes, Aks_ithc - DeployInfrastructuremis/no-changes, Aks_perftest - DeployInfrastructuremis/no-changes, Aks_preview - DeployInfrastructuremis/no-changes, Aks_ptlsbox - DeployInfrastructuremis/no-changes, Aks_aat - DeployInfrastructuremis/no-changes, Network_ptl - NetworkRg/no-changes, Managed_Identity_ptl - Managed_Identity/no-changes, Aks_ptl - DeployInfrastructure/no-changes, Aks_ptl - DeployInfrastructuremis/no-changes, Aks_aat - DeployInfrastructure/no-changes, Aks_sbox - DeployInfrastructure/no-changes, Aks_preview - DeployInfrastructure/no-changes, Aks_demo - DeployInfrastructure/no-changes, Aks_perftest - DeployInfrastructure/no-changes, Network_ptl - DeployInfrastructure/add-or-update, Genesis_sbox - Genesis/add-or-update, Genesis_ptlsbox - Genesis/add-or-update, Genesis_perftest - Genesis/add-or-update, Genesis_aat - Genesis/add-or-update, Genesis_demo - Genesis/add-or-update, Genesis_ithc - Genesis/add-or-update, Genesis_ptl - Genesis/add-or-update

#701 Readding prod to azure-pipeline steps for bootstrapping rollout
  azure-pipelines.yml
Labels: Network_sbox - NetworkRg/no-changes, Network_sbox - DeployInfrastructure/no-changes, Aks_sbox - DeployInfrastructuremis/no-changes, Genesis_preview - Genesis/no-changes, Network_demo - NetworkRg/no-changes, Network_perftest - NetworkRg/no-changes, Network_ithc - NetworkRg/no-changes, Network_ptlsbox - NetworkRg/no-changes, Network_preview - NetworkRg/no-changes, Network_aat - NetworkRg/no-changes, Network_demo - DeployInfrastructure/no-changes, Network_ithc - DeployInfrastructure/no-changes, Network_perftest - DeployInfrastructure/no-changes, Network_ptlsbox - DeployInfrastructure/no-changes, Network_preview - DeployInfrastructure/no-changes, Network_aat - DeployInfrastructure/no-changes, Aks_ithc - DeployInfrastructure/add-or-update, Aks_ptlsbox - DeployInfrastructure/no-changes, Aks_demo - DeployInfrastructuremis/no-changes, Aks_ithc - DeployInfrastructuremis/no-changes, Aks_perftest - DeployInfrastructuremis/no-changes, Aks_preview - DeployInfrastructuremis/no-changes, Aks_ptlsbox - DeployInfrastructuremis/no-changes, Aks_aat - DeployInfrastructuremis/no-changes, Network_ptl - NetworkRg/no-changes, Network_prod - NetworkRg/no-changes, Network_ptl - DeployInfrastructure/no-changes, Managed_Identity_ptl - Managed_Identity/no-changes, Aks_ptl - DeployInfrastructure/no-changes, Aks_prod - DeployInfrastructure/add-or-update, Aks_ptl - DeployInfrastructuremis/no-changes, Aks_prod - DeployInfrastructuremis/no-changes, Aks_aat - DeployInfrastructure/no-changes, Aks_sbox - DeployInfrastructure/no-changes, Managed_Identity_aat - Managed_Identity/no-changes, Aks_preview - DeployInfrastructure/no-changes, Aks_demo - DeployInfrastructure/no-changes, Aks_perftest - DeployInfrastructure/no-changes, Network_prod - DeployInfrastructure/add-or-update, Genesis_sbox - Genesis/add-or-update, Genesis_ptlsbox - Genesis/add-or-update, Genesis_perftest - Genesis/add-or-update, Genesis_aat - Genesis/add-or-update, Genesis_demo - Genesis/add-or-update, Genesis_ithc - Genesis/add-or-update, Genesis_ptl - Genesis/add-or-update, Genesis_prod - Genesis/add-or-update
